image: node:latest

stages:
  - assembly
  - build
  - test
  - publish

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull-push

GatsbyBuild:
  stage: build
  cache:
    <<: *global_cache
  script:
    - yarn install --silent
    - yarn build
  artifacts:
    paths:
      - ./public/*
      - ./functions/*

NetlifyPublish:
  stage: publish
  cache: {}
  script:
    - yarn global add netlify-cli
    - netlify deploy --auth $NETLIFY_AUTH_TOKEN --site $NETLIFY_SITE_ID --prod
  dependencies:
    - GatsbyBuild
